// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'company.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Company _$$_CompanyFromJson(Map<String, dynamic> json) => _$_Company(
      json['出表日期'] as String,
      json['公司代號'] as String,
      json['公司名稱'] as String,
      json['公司簡稱'] as String,
      json['外國企業註冊地國'] as String,
      json['產業別'] as String,
      json['住址'] as String,
      json['營利事業統一編號'] as String,
      json['董事長'] as String,
      json['總經理'] as String,
      json['發言人'] as String,
      json['發言人職稱'] as String,
      json['代理發言人'] as String,
      json['總機電話'] as String,
      json['成立日期'] as String,
      json['上市日期'] as String,
      json['普通股每股面額'] as String,
      json['實收資本額'] as String,
      json['私募股數'] as String,
      json['特別股'] as String,
      json['編制財務報表類型'] as String,
      json['股票過戶機構'] as String,
      json['過戶電話'] as String,
      json['過戶地址'] as String,
      json['簽證會計師事務所'] as String,
      json['簽證會計師1'] as String,
      json['簽證會計師2'] as String,
      json['英文簡稱'] as String,
      json['英文通訊地址'] as String,
      json['傳真機號碼'] as String,
      json['電子郵件信箱'] as String,
      json['網址'] as String,
    );

Map<String, dynamic> _$$_CompanyToJson(_$_Company instance) =>
    <String, dynamic>{
      '出表日期': instance.a,
      '公司代號': instance.b,
      '公司名稱': instance.c,
      '公司簡稱': instance.d,
      '外國企業註冊地國': instance.e,
      '產業別': instance.f,
      '住址': instance.g,
      '營利事業統一編號': instance.h,
      '董事長': instance.i,
      '總經理': instance.j,
      '發言人': instance.k,
      '發言人職稱': instance.l,
      '代理發言人': instance.m,
      '總機電話': instance.n,
      '成立日期': instance.o,
      '上市日期': instance.p,
      '普通股每股面額': instance.q,
      '實收資本額': instance.r,
      '私募股數': instance.s,
      '特別股': instance.t,
      '編制財務報表類型': instance.u,
      '股票過戶機構': instance.v,
      '過戶電話': instance.w,
      '過戶地址': instance.x,
      '簽證會計師事務所': instance.y,
      '簽證會計師1': instance.z,
      '簽證會計師2': instance.a1,
      '英文簡稱': instance.a2,
      '英文通訊地址': instance.a3,
      '傳真機號碼': instance.a4,
      '電子郵件信箱': instance.a5,
      '網址': instance.a6,
    };
